ENVIRONMENT:
  MAX_EPISODE_STEPS: 10000
SIMULATOR:
  ACTION_SPACE_CONFIG: "spring-v0"
  TURN_ANGLE: 1
  TILT_ANGLE: 5
  FORWARD_STEP_SIZE: 0.1
  AGENT_0:
    SENSORS: ['RGB_SENSOR','RGB_SENSOR1','SEMANTIC_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 1280
    HEIGHT: 720
    HFOV: 65
    POSITION:   [0, 1.3, 0.577]
    ORIENTATION: [-1.1, 0.0, 0.0]
    # [-0.47, 1.40, 0]
    # POSITION:   [0, 0.2, 0.3]
    # ORIENTATION: [-0.73, 0, 0.0]
  RGB_SENSOR1:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 90
    POSITION:   [0.1, 1.25, 0]
    ORIENTATION: [0.0, 0.0, 0.0]
    TYPE: "HabitatSimRGBSensor1"
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    POSITION:   [-0.1, 1.25, 0]
    ORIENTATION: [0.0, 0.0, 0.0]
  TYPE: SpringSim-v0
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  POSSIBLE_ACTIONS: ['STOP', 'MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'LOOK_UP', 'LOOK_DOWN']

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'TOP_DOWN_MAP']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
